import bagIcon from "@/assets/icons/handbag.svg";

type SidebarItem = {
  title: string;
  url?: string;
  icon: { src: string };
  submenu?: {
    title: string;
    url: string;
  }[];
};
export const commonSidebarItems: SidebarItem[] = [
  {
    title: "Bags",
    icon: bagIcon,
    submenu: [
      { title: "Purse", url: "/shop/purse" },
      { title: "Briefcases", url: "/shop/briefcase" },
      { title: "Money Clip", url: "/shop/money-clip" },
      { title: "Wallet", url: "/shop/wallet" },
      { title: "Backpack", url: "/shop/backpack" },
      { title: "Travel Bag", url: "/shop/travel-bag" },
      { title: "Card Holder", url: "/shop/card-holder" },
      { title: "Laptop Bag", url: "/shop/laptop-bag" },
      { title: "Suitcase", url: "/shop/suitcase" },
      { title: "Waist Bag", url: "/shop/waist-bag" },
      { title: "Hand Bag", url: "/shop/hand-bag" },
      { title: "Gift Box", url: "/shop/gift-box" },
    ],
  },

  {
    title: "Jewelry",
    icon: bagIcon,
    submenu: [
      { title: "Bracelet", url: "/shop/bracelet" },
      { title: "Earrings", url: "/shop/earrings" },
      { title: "Jewelry Case", url: "/shop/jewelry-case" },
      { title: "Necklace", url: "/shop/necklace" },
      { title: "Bridal Jewelry", url: "/shop/bridal-jewelry" },
      { title: "Crown", url: "/shop/crown" },
      { title: "Pendant", url: "/shop/pendant" },
      { title: "Bangle", url: "/shop/bangle" },
      { title: "Ring", url: "/shop/ring" },
      { title: "Anklet", url: "/shop/anklet" },
      { title: "Tiara", url: "/shop/tiara" },
      { title: "Belly Chain", url: "/shop/belly-chain" },
      { title: "Jewelry Box", url: "/shop/jewelry-box" },
      { title: "Pin Brooch", url: "/shop/pin-brooch" },
      { title: "Fashion Jewelry", url: "/shop/fashion-jewelry" },
    ],
  },
  {
    title: "Shoes",
    icon: bagIcon, // replace with your actual icon variable
    submenu: [
      { title: "Men Shoes", url: "/shop/men-shoes" },
      { title: "Men Boot", url: "/shop/men-boot" },
      { title: "Ladies Shoes", url: "/shop/ladies-shoes" },
      { title: "Ladies Boot", url: "/shop/ladies-boot" },
      { title: "High Heels", url: "/shop/high-heels" },
      { title: "Formal Shoes", url: "/shop/formal-shoes" },
      { title: "Sandals", url: "/shop/sandals" },
      { title: "Running Shoes", url: "/shop/running-shoes" },
      { title: "Casual Shoes", url: "/shop/casual-shoes" },
      { title: "Loafers", url: "/shop/loafers" },
      { title: "Sports Shoe", url: "/shop/sports-shoe" },
      { title: "Baby Shoes", url: "/shop/baby-shoes" },
      { title: "Low Top Shoe", url: "/shop/low-top-shoe" },
      { title: "Rain Boot", url: "/shop/rain-boot" },
      { title: "Football Shoes", url: "/shop/football-shoes" },
      { title: "Slippers", url: "/shop/slippers" },
    ],
  },

  {
    title: "Beauty Products",
    icon: bagIcon, // replace with your actual icon variable
    submenu: [
      { title: "Eyeshadow", url: "/shop/eyeshadow" },
      { title: "Eyeliner", url: "/shop/eyeliner" },
      { title: "Face Powder", url: "/shop/face-powder" },
      { title: "Makeup Remover", url: "/shop/makeup-remover" },
      { title: "Eye Brushes", url: "/shop/eye-brushes" },
      { title: "Hair Removal", url: "/shop/hair-removal" },
      { title: "Mirror", url: "/shop/mirror" },
      { title: "Teeth Whitening", url: "/shop/teeth-whitening" },
      { title: "Nail Polish", url: "/shop/nail-polish" },
      { title: "Lip Gloss", url: "/shop/lip-gloss" },
      { title: "Lip Liner", url: "/shop/lip-liner" },
      { title: "Lipstick", url: "/shop/lipstick" },
      { title: "Anti Hair Loss", url: "/shop/anti-hair-loss" },
      { title: "Hairspray", url: "/shop/hairspray" },
      { title: "Hair Dryer", url: "/shop/hair-dryer" },
      { title: "Hair Dye", url: "/shop/hair-dye" },
      { title: "Hair Oil", url: "/shop/hair-oil" },
      { title: "Shower Gel", url: "/shop/shower-gel" },
      { title: "Candles", url: "/shop/candles" },
    ],
  },

  {
    title: "Mens Clothing",
    icon: bagIcon, // Assuming you have an appropriate icon component here
    submenu: [
      { title: "Casual Pants For Men", url: "/shop/casual-pants-men" },
      { title: "Mens Jeans Pant", url: "/shop/jeans-men" },
      { title: "Men Suit", url: "/shop/suit-men" },
      { title: "Leather Jackets For Men", url: "/shop/leather-jacket-men" },
      { title: "Trouser", url: "/shop/trousers-men" },
      { title: "Shirt", url: "/shop/shirt-men" },
      { title: "Shorts", url: "/shop/shorts-men" },
      { title: "Tie Clip", url: "/shop/tie-clip" },
      { title: "Mens Sweater", url: "/shop/mens-sweater" },
      { title: "Boxers", url: "/shop/underwear-boxer" },
      { title: "Mens Hat", url: "/shop/hat-men" },
      { title: "Leather Gloves", url: "/shop/leather-gloves" },
      { title: "Men Sweatpants", url: "/shop/sweatpants-men" },
      { title: "Socks", url: "/shop/socks-men" },
      { title: "Tie", url: "/shop/tie-men" },
      { title: "Bow Ties", url: "/shop/bow-ties" },
      { title: "Gloves", url: "/shop/gloves" },
    ],
  },
  {
    title: "Womens Clothing",
    icon: bagIcon,
    submenu: [
      { title: "Hoodies & Sweatshirts", url: "/shop/hoodies-women" },
      { title: "Womens Suits Blazers", url: "/shop/suits-women" },
      { title: "Bodysuits", url: "/shop/bodysuits-women" },
      { title: "Coats Jackets", url: "/shop/jacket-women" },
      { title: "Swimwear", url: "/shop/swimwear-women" },
      { title: "Bikini Set", url: "/shop/bikini-set" },
      { title: "Skirt", url: "/shop/skirt" },
      { title: "Womens Jeans", url: "/shop/womens-jeans" },
      { title: "Wedding Dresses", url: "/shop/wedding-dresses" },
      { title: "Prom Dresses", url: "/shop/prom-dresses" },
      { title: "Evening Dresses", url: "/shop/evening-dresses" },
      { title: "Cosplay Costumes", url: "/shop/cosplay-costumes" },
      { title: "Bra", url: "/shop/bra" },
      { title: "Panties", url: "/shop/panties" },
      { title: "Women Socks", url: "/shop/women-socks" },
      { title: "Bucket Hats", url: "/shop/bucket-hat" },
      { title: "Belts", url: "/shop/belt-women" },
    ],
  },
  {
    title: "Baby Items",
    icon: bagIcon,
    submenu: [
      { title: "Baby Bottle", url: "/shop/baby-bottle" },
      { title: "Diapers", url: "/shop/diapers" },
      { title: "Potty & Washing", url: "/shop/potty-&-washing" },
      { title: "Water Toys", url: "/shop/water-toys" },
      { title: "Remote Control Toys", url: "/shop/remote-control-toys" },
      { title: "Baby Gift Set", url: "/shop/baby-gift-set" },
      { title: "Baby Dress", url: "/shop/baby-dress" },
      { title: "Baby Socks", url: "/shop/baby-socks" },
      { title: "Baby Swimsuit", url: "/shop/baby-swimsuit" },
      { title: "Baby Jacket", url: "/shop/baby-jacket" },
      { title: "Baby Skirt", url: "/shop/baby-skirt" },
      { title: "Baby Sweater", url: "/shop/baby-sweater" },
      { title: "Baby Shoes", url: "/shop/baby-shoes" },
      { title: "Baby Sports Shoes", url: "/shop/baby-sports-shoes" },
    ],
  },
  {
    title: "Office & School",
    icon: bagIcon,
    submenu: [
      { title: "Ceiling Fan", url: "/shop/ceiling-fan" },
      { title: "Electric Blanket", url: "/shop/electric-blanket" },
      { title: "Fan", url: "/shop/fan" },
      { title: "Heater", url: "/shop/heater" },
      { title: "Air Conditioner", url: "/shop/air-conditioner" },
      { title: "Smart Home", url: "/shop/smart-home" },
      { title: "Led Screen", url: "/shop/led-screen" },
      { title: "Solar Panel", url: "/shop/solar-panel" },
      { title: "Voltage Converter", url: "/shop/voltage-converter" },
      { title: "Dust Protection", url: "/shop/dust-protection" },
      { title: "Pillow", url: "/shop/pillow" },
      { title: "Umbrella", url: "/shop/umbrella" },
      { title: "Calculator", url: "/shop/calculator" },
      { title: "Compass", url: "/shop/compass" },
      { title: "Digital Pen", url: "/shop/digital-pen" },
      { title: "Kindle", url: "/shop/kindle" },
      { title: "Erasers", url: "/shop/erasers" },
      { title: "Tape", url: "/shop/tape" },
      { title: "Whiteboard", url: "/shop/whiteboard" },
      { title: "Scissors", url: "/shop/scissors" },
      { title: "Projector", url: "/shop/projector" },
      { title: "Diary", url: "/shop/diary" },
      { title: "Wrapping Paper", url: "/shop/wrapping-paper" },
      { title: "Laminating Paper", url: "/shop/laminating-paper" },
    ],
  },
  {
    title: "Seasonal Products",
    icon: bagIcon,
    submenu: [
      { title: "Summer", url: "/shop/summer" },
      { title: "Summer Dress", url: "/shop/summer-dress" },
      { title: "Ice Cream Maker", url: "/shop/ice-cream-maker" },
      { title: "Juicer", url: "/shop/juicer" },
      { title: "Neck Fan", url: "/shop/neck-fan" },
      { title: "Umbrella", url: "/shop/umbrella" },
      { title: "Mosquito Killing", url: "/shop/mosquito" },
      { title: "Raincoat", url: "/shop/raincoat" },
      { title: "Waterproof Backpack", url: "/shop/waterproof-backpack" },
      { title: "Autumn", url: "/shop/autumn" },
      { title: "Winter", url: "/shop/winter" },
      { title: "Winter Dress", url: "/shop/winter-dress" },
      { title: "Badminton", url: "/shop/badminton" },
    ],
  },
  {
    title: "Phone accessories",
    icon: bagIcon,
    submenu: [
      { title: "Xiaomi", url: "/shop/xiaomi" },
      { title: "Apple", url: "/shop/apple" },
      { title: "Huawei", url: "/shop/huawei" },
      { title: "Realme", url: "/shop/realme" },
      { title: "One Plus", url: "/shop/one-plus" },
      { title: "Samsung", url: "/shop/samsung" },
      { title: "Google", url: "/shop/google" },
      { title: "Vivo", url: "/shop/vivo-smartphone" },
      { title: "Nokia", url: "/shop/nokia" },
      { title: "Lg", url: "/shop/lg" },
      { title: "Tecno", url: "/shop/tecno" },
      { title: "Htc", url: "/shop/htc" },
      { title: "Motorola", url: "/shop/motorola" },
      { title: "Asus", url: "/shop/asus" },
    ],
  },
  {
    title: "Sports & Fitness",
    icon: bagIcon,
    submenu: [
      { title: "Snowboard", url: "/shop/snowboard" },
      { title: "Jet Ski", url: "/shop/jet-ski" },
      { title: "Swimming", url: "/shop/swimming" },
      { title: "Fishing Rod", url: "/shop/fishing-rod" },
      { title: "Grills & Bbq Equipment", url: "/shop/bbq" },
      { title: "Luggage Lock", url: "/shop/luggage-lock" },
      { title: "Yoga", url: "/shop/yoga" },
      { title: "Tent", url: "/shop/tent" },
    ],
  },
  {
    title: "Entertainment Items",
    icon: bagIcon,
    submenu: [
      { title: "Gopro", url: "/shop/gopro" },
      { title: "Camera", url: "/shop/camera" },
      { title: "Travel Bags", url: "/shop/travel-bags" },
      { title: "Travel Luggage", url: "/shop/luggage" },
      { title: "Travel Pillow", url: "/shop/travel-pillow" },
      { title: "Beanbags", url: "/shop/beanbags" },
      { title: "Tv", url: "/shop/tv" },
      { title: "Movie Poster", url: "/shop/movie-poster" },
      { title: "Popcorn Maker", url: "/shop/popcorn-maker" },
      { title: "Virtual Reality", url: "/shop/vr-box" },
      { title: "Bluetooth Speakers", url: "/shop/bluetooth-speakers" },
      { title: "Drawing Tablet", url: "/shop/drawing-tablet" },
      { title: "Headphone", url: "/shop/headphone" },
      { title: "Ipad", url: "/shop/ipad" },
    ],
  },
  {
    title: "Watches",
    icon: bagIcon,
    submenu: [
      { title: "Watch", url: "/shop/watch" },
      { title: "Womens Watch", url: "/shop/women-watches" },
      { title: "Mens Watches", url: "/shop/mens-watches" },
      { title: "Smart Watch", url: "/shop/smart-watch" },
      { title: "Gshock", url: "/shop/gshock" },
      { title: "Apple Watch", url: "/shop/apple-watch" },
      { title: "Fit Band", url: "/shop/fit-band" },
    ],
  },
  {
    title: "Automobile Items",
    icon: bagIcon,
    submenu: [
      { title: "Automobile", url: "/shop/automobile" },
      { title: "Interior Accessories", url: "/shop/car-interior" },
      { title: "Car Accessories", url: "/shop/car-accessories" },
      { title: "Car Audio", url: "/shop/car-audio" },
      { title: "Motorcycle", url: "/shop/motorcycle" },
      { title: "Motorcycle Accessories", url: "/shop/motorcycle-accessories" },
      { title: "Car Kit", url: "/shop/car-kit" },
    ],
  },
];
