import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

// Load the font (choose subset, weight if needed)
const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // adjust weights as needed
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="referrer" content="no-referrer" /> t
      <body className={`bg-[#f7f7f7] ${jost.className} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
